[tool.poetry]
name = "firestarter"
version = "0.1.0"
description = ""
authors = ["Javier Gomez Rodriguez <javiergr@ext.zara.com>"]

[tool.poetry.scripts]
dagger = "firestarter.parser:parse"

[tool.poetry.dependencies]
python = "^3.11"
firestarter-workflows = {git = "https://github.com/prefapp/firestarter-workflows", rev = "main"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
