[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Jose Alvarez <jose.alvarez@prefapp.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
