name: Dagger magic
on:
  workflow_dispatch:
jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call composite action
        uses: prefapp/run-dagger-py@main
        with:
          workflow: pr_verify
          config_file: .github/firestarter.yml
          vars: |
            foo='bar'
          secrets: |
            secret1='topsecret'
