name: Dagger magic
on:
  workflow_dispatch:
jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run PR verify workflow
        uses: prefapp/run-dagger-py@main
        with:
          workflow: pr_verify
          config_file: .github/firestarter_pr_verify.yml
          pyproject_path: .dagger
          vars: |
            foo="bar"
          secrets: |
            secret1="topsecret"
